### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by exquest** [arteria/django-background-tasks#74] opened 2017-01-17 21:30 UTC
So I installed the software correctly and did a manual migration on the app to get the database tables working. I've created a task by adding the `@background()` helper to a function. 

I'm manually running `python manage.py process_tasks` to process the tasks. When I run the function I added the `@background()` to through a management command it doesn't do anything. It creates the 'Task' in the database to be processed but fails to attempt.

I'm running Django 1.10... any suggestions?

**Comment by jvamvas** [comment] 2017-01-18 10:20
In the created Task, look for any data on
* Run at
* Attempts
* Failed at
* Last error
* Locked by/at

For instance, "Failed at" and "Last error" indicate that there was an error when the task was processed. If "Locked by/at" are set, we know that processing has started at some point.

**Comment by exquest** [comment] 2017-01-18 18:42
Here is my process:
I added the `@background(schedule=10)` to a function run by my management command.
I opened up a shell and ran `python manage.py process_tasks`. 
I left this shell open and opened another shell. In the new shell I ran the management command that had the decorator attached to the function it ran. The command seems to have been run and the shell gives me a new prompt.
Opening up the admin panel I get this as the new task that was created:

![ubuntu_64-bit_14_04_1](https://cloud.githubusercontent.com/assets/4186413/22077544/6dc321e2-dd69-11e6-823a-b4bd03ee2d6f.png)

... nothing happened ... I waited about 10 minutes and still nothing

as a second test I created a view that just ran the command, went to the url. It created the task in the database (and in the admin) but again it showed no signs of running.

This is a screenshot of the new task I created through the view:

![ubuntu_64-bit_14_04_1](https://cloud.githubusercontent.com/assets/4186413/22077813/99e3d108-dd6a-11e6-9c9e-ec6b33c934ca.png)

It does not seem that the process has started

**Comment by exquest** [comment] 2017-01-18 19:11
Well this is odd. I ran the `python manage.py process_tasks --traceback --log-std --log-level DEBUG` and now it works every time even if I run just `python manage.py process_tasks`.

I'm glad this works not but this is odd.

I'm going to try this on a new dummy project in a bit and see if I can duplicate this.

**Comment by sla-shi** [comment] 2017-01-29 10:26
I can confirm the issue.  The process_tasks does nothing with the tasks in the queue.

**Comment by sla-shi** [comment] 2017-01-29 12:02
I think the problem is that the module name preceding the method name is different when the task is created and executed.

In my case the task name was `__main__.report1` when created from a command line script, and the after I moved `report1` into a module it became `mymodule.tasks.report1`. And now the process_task can find the method and invoke it.

**Comment by sumitalp** [comment] 2017-02-24 09:38
In my case, I had written background tasks in a different file like `mymodule.file1` where no `tasks.py` file existed in `mymodule` folder. After spending long hours I decided to put a `tasks.py` file and import those tasks from `file1.py` to `tasks.py` and surprisingly it works. I urge to @philippeowagner to update README regarding this issue.

**Comment by philippeowagner** [comment] 2017-02-24 09:55
The tasks are picked up from the `tasks.py` file, that is read by autodicover, which is [defined here](https://github.com/arteria/django-background-tasks/blob/master/background_task/tasks.py#L296). Will update the README and closing this...

**Closed** 2017-02-24 10:12 UTC

**Comment by sumanshusamarora** [comment] 2020-05-26 12:36
Was anyone able to solve this? I am facing the exact same issue. The task gets scheduled in DB but is not discovered by process_task. The background function is called from outside of main project to schedule (and it works fine) but the function definition is under tasks.py into an application.

**Comment by philippeowagner** [comment] 2020-05-26 12:49
Put the code decorated with `@background`in the `tasks.py` file.

**Comment by sumanshusamarora** [comment] 2020-05-26 12:57
@philippeowagner It already exists in tasks.py.

@background(schedule=0)
def release_to_kafka_topic_at_certain_time(email_guid=None, event_id=None, type='DD'):
    print(email_guid, event_id, type)

**Comment by sumanshusamarora** [comment] 2020-05-26 12:58
Here is the admin panel snapshot showing tasks existing in database.

![image](https://user-images.githubusercontent.com/45642655/82903479-5b186600-9fa4-11ea-907b-e4cca6d8ff82.png)

**Comment by alikadv** [comment] 2020-08-06 18:33
you need to run python "manage.py process_tasks" this is written in instructions https://django-background-tasks.readthedocs.io/en/latest/#running-tasks

**Comment by actlikewill** [comment] 2022-06-09 05:31
I can't get it to work. I have my function in tasks.py and I have run python manage.py process_tasks in another terminal.
